# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Infineon Technologies AG
# SPDX-License-Identifier: MIT

version = 1

[[annotations]] 
path = ["settings.gradle", "build.gradle", "app/build.gradle", "gradle.properties"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 Infineon Technologies AG"
SPDX-License-Identifier = "MIT"

[[annotations]] 
path = "app/src/main/res/**/**.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 Infineon Technologies AG"
SPDX-License-Identifier = "CC-BY-NC-ND-4.0"

[[annotations]] 
path = "docs/images/**.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 Infineon Technologies AG"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]] 
path = ["**/gradlew", "**/gradlew.bat", "**/gradle/wrapper/gradle-wrapper.jar", "**/gradle/wrapper/gradle-wrapper.properties"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2021 the original authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]] 
path = "app/src/main/res/font/source_sans_pro_**.ttf"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014-2021 Adobe (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"